## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [ ]:
import numpy as np

def numpy_array(N: int):
    return np.arange(N)[::-1]
def numpy_array_(N: int):
    return np.arange(start=N-1, stop=-1, step=-1)

In [ ]:
%%time
numpy_array(34)

CPU times: user 44 µs, sys: 0 ns, total: 44 µs
Wall time: 48.2 µs


array([33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
%%time
numpy_array_(10)

CPU times: user 29 µs, sys: 2 µs, total: 31 µs
Wall time: 34.3 µs


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [ ]:
def diag_array(N: int):
    return np.diag(np.arange(N)[::-1]).sum()

diag_array(35)

595

## Задание 3
Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

In [ ]:
M = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
v = np.array([4., 12., -3.])
x = np.linalg.solve(M, v)
print(f'x = {round(x[0], 2)}, y = {round(x[1], 2)}, z = {round(x[2], 2)}')

x = 0.47, y = 3.84, z = -5.56


In [ ]:
print(M @ x, v, np.isclose(M @ x, v), sep='\n')

[ 4. 12. -3.]
[ 4. 12. -3.]
[ True  True  True]
